### ISSUE TITLE
Some comments in metronome.js about pitch seem wrong

### ISSUE THREAD

**Issue by lflee** [cwilso/metronome#13]
I am not good at music or coding at all, so I am sorry if my question is too stupid.

Some comments in metronome.js (https://github.com/cwilso/metronome/blob/master/js/metronome.js) about pitch confuse me -
Line 58 - if (beatNumber % 16 === 0)    // beat 0 == **low pitch** <- should this actually a high pitch note?
               osc.frequency.value = 880.0;
Line 62    else                        // other 16th notes = **high pitch**  <- should these actually low pitch notes?
                 osc.frequency.value = 220.0;

**Comment by cwilso** [comment]
Oops.  Switched the comments.  :)  thanks!
