### ISSUE TITLE
Nothing happens in Safari on iOS

### ISSUE THREAD

**Issue by hmoffatt** [cwilso/metronome#14]
When I try the demo in iOS on Safari, nothing happens. There's nothing in the error console either. It's ok on desktop Safari.

**Comment by cwilso** [comment]
Yeah, that's because Safari haphazardly blocks the AudioContext from running unless it's created from an interaction event.

**Comment by hmoffatt** [comment]
Right, playing a silent buffer in the first call to play() got things working. Thanks.

**Comment by Win10Developer** [comment]
Hey hmoffatt, can you show exactly how this works please? I'm not up to speed with HTML5, etc, but would love to get this working on iOs myself. Thanks

**Comment by hmoffatt** [comment]
@Win10Developer I've put my fix in https://github.com/hmoffatt/metronome

**Comment by hmoffatt** [comment]
@cwilso right, thanks. I knew Safari muted the sound until it's created from an interaction event but in this case it looks like the AudioContext's currentTime doesn't even start. Playing a dummy buffer before starting the scheduling gets it going.
