### ISSUE TITLE
Metronome no long runs in background tab in Chrome 55

### ISSUE THREAD

**Issue by tambien** [cwilso/metronome#17]
Hi Chris, 

I use this approach for metronome timing in Tone.js. One great thing about using a WebWorker like you do is that it runs in a background tab. But, I was just running this on Chrome Canary (55.0.2856.0) and I noticed this is no longer the case. It seems to get throttled just like events scheduled from requestAnimationFrame. 

Background scheduling of Web Audio is a wonderful thing and it'd be a shame to lose it in Chrome (still works the same in Safari and FF though). I'm wondering if you have any thoughts or work arounds for this.

Thanks!

**Comment by tambien** [comment]
I just filed this as [a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=646163) with chromium.

**Comment by eladg** [comment]
some updates made on May on a related ticket at Chromium

https://bugs.chromium.org/p/chromium/issues/detail?id=642321

**Comment by hinzed1127** [comment]
this appears to be resolved now. The ticket is closed and should work as of version 60.0.3092.0.
